### ISSUE TITLE
Add fn-locks to smartkeyboard

### ISSUE THREAD

**Issue by h-david-a** [echo-lalia/Cardputer-MicroHydra#52]
It is super annoying to click arrows multiple times to navigate around big files.
Holding fn or ctrl modifiers is also painful :)
I propose to:
1. Implement key repeats (holding a key will repeat the effect)
2. Implement modifier-keys locks (e.g by triple click).  That would require adding some visual indicator (I'd propose a popup in top-right corner with 4 small squares to indicate active locks)

**Comment by echo-lalia** [comment]
Are you talking about HyDE.py (the text editor)? 

If you are, I agree :)

I duplicated the old keyboard module into a new one I'm just calling "smartkeyboard.py". It has key repeating built-in and is capable of automatically modifying the config on-the-fly using keyboard shortcuts. 

I'm using a new module so that the old one can remain as a lower-memory alternative. Most of the built-in apps have been switched over to the new smartkeyboard module, but HyDE has not yet (and the only reason, is that it has some conflicting keyboard shortcuts that'll need to be changed first; it definitely should be migrated over to the new module).

The smartkeyboard module doesn't have support for locking keys yet, but that sounds like a good idea to me.   
It could probably be added to smartkeyboard, and then all of the system apps can inherit that functionality.

**Comment by echo-lalia** [comment]
Just modified HyDE to use smartkeyboard. Now key repetition works. 

smartkeyboard module just needs to implement locking mod keys, now :)

**Comment by echo-lalia** [comment]
FYI: I have added locking function keys to the experimental branch (which I intend to be MicroHydra 2.0 once I'm done), and it will work from any app using the keyboard module 😊
